name: Build and compatibility test generated scripts

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - id: dotnet-versions
        shell: bash
        run: |
          {
            echo 'versions<<EOF'
            {
              echo '8.0.x'
              node scripts/list-build-output.mjs majors | awk '{ print $1 ".0.x" }'
            } | sort -u
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.dotnet-versions.outputs.versions }}
      - run: npm ci --ignore-scripts
      - env: { GITHUB_TOKEN: "${{ github.token }}" }
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages/*.nupkg

  smoke-test:
    needs: build-package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        hosting-model: [Server, WebAssembly]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: 8.0.x }
      - uses: actions/download-artifact@v4
        with: { name: packages, path: artifacts/packages }
      - run: dotnet pack src/LegacyBlazorJs/LegacyBlazorJs.csproj -o artifacts/packages -p:PackageVersion=8.0.0
        shell: bash
      - run: npm ci --ignore-scripts
      - run: dotnet test tests/PlaywrightTest/PlaywrightTest.csproj
        env:
          SMOKE_TEST_HOSTING_MODEL: ${{ matrix.hosting-model }}

  compatibility-test:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: dotnet-versions
        shell: bash
        run: |
          {
            echo 'versions<<EOF'
            {
              echo '8.0.x'
              node scripts/list-build-output.mjs majors | awk '{ print $1 ".0.x" }'
            } | sort -u
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.dotnet-versions.outputs.versions }}
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/download-artifact@v4
        with: { name: packages, path: artifacts/packages }
      - run: dotnet pack src/LegacyBlazorJs/LegacyBlazorJs.csproj -o artifacts/packages -p:PackageVersion=8.0.0
        shell: bash
      - run: npm ci --ignore-scripts
      - run: npm run test:compat:update-readme
      - uses: actions/upload-artifact@v4
        with:
          name: compatibility-results
          path: |
            artifacts/compatibility/results.json
            README.md
